//============ Login for Farmer and Cistomer =====================

###
//login user (both farmer and customer)
POST http://localhost:3000/login/ HTTP/1.1
Content-Type: application/json

{"email":"ayush@gmail.com", "password":"abc123"}

//============== Signup For farmer ===================================

###
//user farmer signup1 with product details
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{"first_name":"Ayush1", "last_name": "Bh1", "email": "ayush2@gmail.com", "password":"abc123", 
"role": "farmer", "address":"Ottumuwa","product":[{"product_name":"Apple", 
"product_description":"Red apple from Humla","price":"$1.5", "quantity":1, 
"product_image":"https://picsum.photos/200/300"}]}

###
//user farmer signup2 with product details
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{"first_name":"Ayush4", "last_name": "Bh4", "email": "ayush4@gmail.com", "password":"abc123", 
"role": "farmer", "address":"Ottumuwa","product":[{"product_name":"Apple", 
"product_description":"Red apple from Humla","price":"$1.5", "quantity":1, 
"product_image":"https://picsum.photos/200/300"}]}

###
//user farmer signup without product details
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{"first_name":"Ayush2", "last_name": "Bh2", "email": "ayush3@gmail.com", "password":"abc123", 
"role": "farmer", "address":"Ottumuwa"}

//=================== For farmer ===============================
//To fetch all users whose role is farmer
###
GET http://localhost:3000/farmer HTTP/1.1
Content-Type: application/json

###
//To get farmer by his id
GET http://localhost:3000/farmer/5f3200783a70aa27529f83fb HTTP/1.1
Content-Type: application/json

###
//To get particular farmer with his all products and it gives farmer id too
GET http://localhost:3000/farmer/5f3200783a70aa27529f83fb/5f320ebaec5d1547479f0811 HTTP/1.1
Content-Type: application/json

###
//add farmer products
POST http://localhost:3000/farmer/5f3200783a70aa27529f83fb/add HTTP/1.1
Content-Type: application/json

{"product":[{"product_name":"Pineapple", 
"product_description":"It is from Butwal","price":"$1.25", "quantity":5, 
"product_image":"https://picsum.photos/200/300"}]}

###
//update farmer product by id
PATCH http://localhost:3000/farmer/5f31bffef040b7e404545b69/5f31bffef040b7e404545b6a HTTP/1.1
Content-Type: application/json

{"product":[{"product_name":"banana", 
"product_description":"Orange from Humla","price":"$1.5", "quantity":1, 
"product_image":"https://picsum.photos/200/300"}]}

###
//delete farmer product by id
DELETE http://localhost:3000/farmer/5f3200783a70aa27529f83fb/5f320ebdec5d1547479f0813/ HTTP/1.1
Content-Type: application/json

//====================== Sign up For Customer===================================

###
//user signup for customer
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{"first_name":"Ayush", "last_name": "Bh", "email": "ayush@gmail.com", "password":"abc123", 
"role":"customer", "address":"Fairfield", "reputation":4}

//=================== For Customer ===============================================
//To fetch all users whose role is customer
###
GET http://localhost:3000/customer HTTP/1.1
Content-Type: application/json

//Customer to fetch all products by farmerid
###
GET http://localhost:3000/customer/5f3200783a70aa27529f83fb HTTP/1.1
Content-Type: application/json

//===== Order by customer 1
//Customer to post all orders once he checkout
###
POST http://localhost:3000/customer/orders HTTP/1.1
Content-Type: application/json

{"order_items": [{"product_name": "apple", "quantity": 1, "item_total": 3}],
 "total_price": 12, "status": "pending", "pickup_date": "15/02/2020",
 "farmer": {"id": "5f3200783a70aa27529f83fb", "first_name":"Ayush1", "last_name":"Bh1", 
  "email": "npaudel@miu.edu", "address":"Ottumuwa"},"customer": {"id": "5f3161de3e2bac2ab6073f1b", 
  "first_name":"Ayush", "last_name":"Bh", "email":"npaudel@miu.edu"}}

//===== Order by customer 2
###
POST http://localhost:3000/customer/orders HTTP/1.1
Content-Type: application/json

{"order_items": [{"product_name": "apple", "quantity": 1, "item_total": 3}],
 "total_price": 12, "status": "pending", "pickup_date": "15/02/2020",
 "farmer": {"id":"5f3200783a70aa27529f83fb", "first_name":"Ayush1", "last_name":"Bh1", 
  "email":"npaudel@miu.edu", "address":"Ottumuwa"},"customer": {"id":"5f3161de3e2bac2ab6073f1c", 
  "first_name":"Ayush", "last_name":"Bh", "email":"npaudel@miu.edu"}}

//by Customer for his all orders by customerid
###
GET http://localhost:3000/customer/orders/5f3161de3e2bac2ab6073f1c HTTP/1.1
Content-Type: application/json

//by farmer for his all orders by farmers id
###
GET http://localhost:3000/farmer/orders/5f3200783a70aa27529f83fb HTTP/1.1
Content-Type: application/json

//change status by farmer from pending to ready
###
PATCH http://localhost:3000/farmer/orders/5f32be13c71f854cbe9f7209/ready HTTP/1.1
Content-Type: application/json

//change status by farmer from ready to completed
###
PATCH http://localhost:3000/farmer/orders/5f32be13c71f854cbe9f7209/completed HTTP/1.1
Content-Type: application/json